-
  name: Deploy a web application
  hosts: db_web_server1, db_web_server2
  tasks:
    - name: Install all required dependencies
      apt: name={{ item }} state=present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb

    - include: tasks/deploy_db.yml
    - include: task/deploy_web.yml
